### ISSUE TITLE
IP Address as Dynamic Field

### ISSUE THREAD

**Issue by elessar072** [zaus/forms-3rdparty-dynamicfields#4]
I've been struggling to get the IP address to be forwarded using the plugin :( I noticed somebody else had this problem here, to which you answered: http://drzaus.com/plugins/update-to-forms-%E2%80%93-3rdparty-integration-for-wordpress-contact-form-7-and-gravity-forms . 

Would appreciate any help you can provide! 
Thanks,
Dan.

**Comment by zaus** [comment]
It's a little embarrassing I haven't added this feature yet.  Should be
trivial to include - I won't be able to for another week, but I could point
you in the right direction (bonus if you're into submitting a pull request).

**Comment by zaus** [comment]
Add something like the following
http://www.wpbeginner.com/wp-tutorials/how-to-display-a-users-ip-address-in-wordpress/
to the switch statement in the `replace` function (and add the same label
to the `is_replace` function).

**Comment by elessar072** [comment]
No worries - thanks for taking a look! I actually managed to patch a solution together by editing your plugin and calling this function that I placed in functions.php of my wordpress. But it's not a self-contained solution, as it would be if i were adding it to the switch statement. I'll try to submit a pull request with the changes later today.

**Comment by zaus** [comment]
Feature live as part of v0.6 in b2e710574d38f6dafcf9816de8ad026a5083dca4

Just use `##IP##``
